@startuml ejercicio7

Class Proyecto{
    Nombre: 1 Texto
    Fecha de inicio: 1 Tiempo
    Fecha de fin: 0..1 Tiempo
}

Class MiembroDelEquipo{
    Nombre: 1 Texto
    Apellidos: 1 Texto
    Rol: 0..* Texto
}

Class LugarDeActuacion{
    Nombre: 0..*
    Coordenada X: 1 Numero
    Coordenada Y: 1 Numero
}

@enduml
