@startuml ejercicio13

Object pol1{
}

Object pt1{
  x:-10
  y:10
}

Object pt2{
  x:10
  y:10
}

Object pt3{
  x:-10
  y:-10
}

Object pt4{
  x:10
  y:-10
}

pt1 --o pol1  :posee <
pt2 --o pol1  :posee <
pt3 --o pol1  :posee <
pt4 --o pol1  :posee <


@enduml