@startuml ejercicio16
Class Persona {
Nombre: 1 Texto
Primer apellido: 1 Texto
Segundo apellido: 0..1 Texto
Fecha de nacimiento: 1 Tiempo
Sexo: 1 Texto
Numero de indentificacion: 0..1 Texto
}

Persona "Cónyuge 0..1" -- "Cónyuge 0..1" Persona : Está casada con
Persona "Progenitor 2" -- "Hija 0..*" Persona : Es hija de
@enduml