@startuml ejercicio11
Class Cuadro{
    Titulo: 0..* Texto 
    Cronologia: 1 Tiempo
    Tecnica: 1 enum Tecnica
    Sub-tecnica: 1 enum Sub-Tecnica
    Material del soporte: 1 enum Material
    Autor: 1 Texto
    Estado de conservacion: 1 enum Estado de conservacion
}

Class Lugar{
  Institucion: 1 texto
  Ciudad: 1 Texto
  Pais: 1 Texto
}

enum Tecnica{
    Acuarela
    Oleo
    Pastel
    Fresco
}

enum Sub-Tecnica{
    Sfumato
    Pincelada simple
    Collage
    Veladura
}

enum Material{
    Madera
        Alamo
        Nogal
    Lienzo
    Obra
}

enum EstadoDeConservacion{
    Excelente
    Bueno
    Regular
    Malo
    Destruido
}

Cuadro "0..1 Original" -- "0..* Replica" Cuadro : Es replica de <
Lugar "1" -- "0..*" Cuadro: Se localiza en <





@enduml
